version: "3.7"
services:
  app:
    container_name: app
    build: app/
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/:/app/
    ports:
     - 8080:8080
    command: flask run --host=0.0.0.0 -p 8080